name: Frontend Deploy To Dev
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/**

env:
  DEV_DIR: /home/${{ vars.SSH_USERNAME }}/docker/nginx/html/dev.muenstr

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - working-directory: frontend
        run: npm ci
      - working-directory: frontend
        run: npm run build --if-present

      - uses: actions/upload-artifact@v3
        with:
          name: fe-dist
          path: frontend/dist/

  copy:
    name: Copy Dist Files
    runs-on: ubuntu-latest
    environment: dev
    needs: build
    steps:

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: fe-dist
          path: .

      - name: Copy Files via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{vars.SSH_HOST}}
          key: ${{secrets.SSH_KEY}} # Private key of the server
          username: ${{ vars.SSH_USERNAME }}
          source: .
          target: ${{env.DEV_DIR}}